[package]
name = "jarvil"
version = "0.1.0"
edition = "2018"
authors = ["Bhavya Bhatt bhavyabhatt17@gmail.com"]

[dependencies]
rustc-hash = { version = "1.1" }
colored = "2.0.0"
jarvil-macros = { path = "jarvil-macros" }
text-size = "1.1.0"