[package]
name = "jarvil-py"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true

[dependencies]
jarvil-parser = { path = "../jarvil-parser" }
miette = { version = "7.6", features = ["fancy"] }
rustc-hash = { version = "2.1" }

[dev-dependencies]
insta = { version = "1", features = ["glob"] }
