[package]
name = "jarvil-lsp"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true

[dependencies]
jarvil-parser = { path = "../jarvil-parser" }
tower-lsp = "0.20"
tokio = { version = "1", features = ["rt-multi-thread", "macros", "io-std", "time"] }
