[package]
name = "anyon"
version = "0.1.0"
edition = "2018"
authors = ["Bhavya Bhatt bhavyabhatt17@gmail.com"]

[dependencies]
clap = { version = "4.5.4", features = ["derive"] }
compiler = { path = "../../compiler" }
miette = { version = "5.3.0" }
owo-colors = "3.5.0"
